### ISSUE TITLE
Add support for PULL_REQUEST_TEMPLATE

### ISSUE THREAD

**Issue by jd** [jd/git-pull-request#17]
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

**Comment by 4383** [comment]
@jd do you have any ideas on how to work with different PR templates?
Each project can define its own PR templates so it's hard to standardize this feature.
I'm interesting to help your team to improve this project so more informations about this are welcome!

**Comment by jd** [comment]
The point is to use the template provided in the `.github` repository or in any place support by GitHub. Did you check the original link in the bug report?

**Comment by 4383** [comment]
yes I've already check this link.
My question is rather to have an idea of ​​how to work with sophisticated templates content (like project ansible per example).
Ansible github issues template ask for logs output per example (before changes, after changes) and a lot of other stuffs (ansible --version output, etc...) so... semantical content are requested and manual actions are needed.

**Comment by 4383** [comment]
When I said issues I make a mistake I want to talk about PR instead of issues

**Comment by jd** [comment]
Do you have an example of these Ansible templates?

**Comment by jd** [comment]
As far as I can see people are using it to publish pull requests so that's good. I don't see how hard it is to standardize it, as you say?

**Comment by 4383** [comment]
Maybe I'm wrong or I misunderstood your idea.

In the first time I think you want to fill the PR template automaticaly when the PR was created so my question for sophisticated templates.

But now I think you just want to add  a filled PR template content in parameter to the github API [pygithub ](http://pygithub.readthedocs.io/en/latest/) via the body argument of the `create_pull` method  instead of using the latest messages commits (or the `git pull-request --message` content).

I'm wrong?

**Comment by jd** [comment]
Yep, that's the spirit of the issues. Use that file as a default body.

**Comment by jd** [comment]
Closed via https://github.com/jd/git-pull-request/pull/22
